apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-1
spec:
  replicas: 2
  selector:
   matchLabels:
     app: my-deployment-1
template:
    metadata:
      labels:
        app: my-deployment-1
    spec:
      containers:
        -name: node.js-app-container
        image:  ausaf009/node.js-app:latest
        imagePullPolicy: Always
        port:
        - containerPort: 3005
