apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-deployment
  containers:
    - image: ausaf009/nodejs-app-image::master-fd3858d4d32a739850bec40094bd8cb2c6061b75
template:
  metadata:
    labels:
      app: my-deployment
  spec:
    containers:
      -name: node.js-app-container
      image: ausaf009/node.js-app:latest
      imagePullPolicy: Always
      port:
        - containerPort: 3005
