apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
        - name: my-app-container
          image: ausaf009/nodejs-app-image:master-d5f59dd6ad8a3e3442a306cbfb875263ab824f75
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
  containers:
    - image: ausaf009/nodejs-app-image:master-a3a96010a0cc7ef47121a8db990b720a2e4ca0d9
