apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
        - name: my-app-container
          image: ausaf009/nodejs-app-image:master-3e25aa0541314cb17611c347f81a7130eed5ffaf
          imagePullPolicy: Always
          ports:
            - containerPort: 3005
