apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
        - name: my-app-container
          image: ausaf009/nodejs-app-image:master-0dac30a263bae6521be35ce2a965860f82d5e9e7
          imagePullPolicy: Always
          ports:
            - containerPort: 3005
