name: Build, Push, and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

         

      - uses: actions/checkout@v2
      - name: Set env
        run: echo "GITHUB_BRANCH=$(echo $GITHUB_REF_NAME-$GITHUB_SHA)" >> $GITHUB_ENV  


      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx inspect default --bootstrap
          docker buildx build --file Dockerfile -t ausaf009/node.js-app-image:$GITHUB_REF_NAME-$GITHUB_SHA --load .
          docker images

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: latest

      - name: Push Docker image to Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUBE }} | docker login --username ausaf009 --password-stdin
          docker push ausaf009/node.js-app:latest

      - name: Update manifest file
        run: |
          # Assuming you have a manifest file named k8s.yaml
          git config --global user.email "ausafansari.wohlig@gmail.com"
          git config --global user.name  "ausaf-wohlig"
          yq eval -i '.spec.containers[0].image = "ausaf009/node.js-app:latest"' deploy/manifest.yml

          git add .

          git commit -m "updating newer image"
          git push --set-upstream origin master  



